version: "3.9"
networks:
  mongodb-network:
    name: mongodb-network
    driver: bridge
    ipam:
        config:
          - subnet: 172.16.57.0/24
services:
  cross-ma:
    build:
      context: .
    image: cross-ma:$VERSION
    container_name: cross-ma
    networks:
      - mongodb-network
    ports:
      - "8051:8051"
    environment:
      - TARGET=$TARGET
      - FIREBASE_CREDENTIALS_PATH=$FIREBASE_CREDENTIALS_PATH
    restart: unless-stopped