version: "3.9"
networks:
  mongodb-network:
    name: mongodb-network
    driver: bridge
    ipam:
        config:
          - subnet: 172.16.57.0/24
services:
  accounts-service:
    build:
      context: .
      dockerfile: accounts.Dockerfile
    image: accounts-service:$VERSION
    container_name: accounts-service
    networks:
      - mongodb-network
    ports:
      - "5001:5001"
    environment:
      - TARGET=$TARGET
      - REST_API_USER=${REST_API_USER}
      - REST_API_PASSWORD=${REST_API_PASSWORD}
      - REST_API_BASE_URL=${REST_API_BASE_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - /home/axel/Documents/trading/trading/algorithm/logs:/logs
    restart: unless-stopped