version: "3.9"
networks:
  mongodb-network:
    name: mongodb-network
    driver: bridge
    ipam:
        config:
          - subnet: 172.16.57.0/24
services:
  algo-service:
    build:
      context: .
      dockerfile: algo.Dockerfile
    image: algo-service:$VERSION
    container_name: algo-service
    networks:
      - mongodb-network
    ports:
      - "8060:8060"
    environment:
      - TARGET=${TARGET}
      - REST_API_USER=${REST_API_USER}
      - REST_API_PASSWORD=${REST_API_PASSWORD}
      - ACCOUNTS_REST_API_BASE_URL=${ACCOUNTS_REST_API_BASE_URL}
      - OHLCV_REST_API_BASE_URL=${OHLCV_REST_API_BASE_URL}
      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - BOT_ID=62866a8a56025eccf857fc22
    volumes:
      - ${LOGS_PATH}:/logs
    restart: unless-stopped