version: "3.9"
networks:
  mongodb-network:
    name: mongodb-network
    driver: bridge
    ipam:
        config:
          - subnet: 172.16.57.0/24
services:
  data-service:
    build:
      context: .
    image: data-service:$VERSION
    container_name: data-service
    networks:
      - mongodb-network
    ports:
      - "5000:5000"
    environment:
      - TARGET=$TARGET
      - REST_API_USER=$REST_API_USER
      - REST_API_PASSWORD=$REST_API_PASSWORD
    restart: unless-stopped